POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MzcwNjYyMTYsInVzZXJJZCI6MX0.tt4LVwqB_cPkJvff5OSR3fkF4sYwkaWhOriSoa9P8Zg

{
   "name" : "Tast fguyfedguyfeguyh",
   "description" : "Tast deseeddddc 2",
   "location" : "Tast loc 2",
   "date_time": "2025-01-01T15:30:00.000Z"
}