POST http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwiZXhwIjoxNzM3MDI3NDQxLCJ1c2VySWQiOjJ9.H7iQqrFtOOrFuICPH_Qbm_lmFnS_7GlUFR5nGfYhgIA

